### ISSUE TITLE
Incompatible interface breaks flashlight package CI

### ISSUE THREAD

**Issue by joesis** [getlantern/connmux#4]
@oxtoacart There seems no way to implement `BufferPool` interface. It contains private [`getForFrame`](https://github.com/getlantern/connmux/blob/master/connmux.go#L164) method, which causes an error when building test binary for `flashlight/app` package.

> ~/workspace/go/src/github.com/getlantern/flashlight/app (devel) $ go test
> ../vendor/github.com/getlantern/http-proxy-lantern/http_proxy.go:304: cannot use buffers.Pool() (type *bpool.BytePool) as type connmux.BufferPool in argument to connmux.WrapListener:
	*bpool.BytePool does not implement connmux.BufferPool (missing connmux.getForFrame method)

Interestingly, there's no error when building `http-proxy-lantern` directly.

**Comment by oxtoacart** [comment]
The reason this happened is that the change in http-proxy-lantern depended on a change in http-proxy that was never pulled. It has been pulled now.

See https://github.com/getlantern/http-proxy/pull/99
